spring:
   application:
      name: akeiraPojos
   profiles:
      active: development
   jackson:
      date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
   flyway:
      enabled: true
server:
   port: 9926
   ssl:
      key-store-type: PKCS12
      key-store: /opt/uniphore/u-selfserve/cert/uniphore.pfx
      key-store-password: UniJjsJ2wLehxIe6C
      key-alias: 1
      enabled: false
